# Generated by Django 3.2.20 on 2023-12-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0005_delete_gstr3b'),
        ('vyaparapp', '0011_paymentout'),
    ]

    operations = [
    ]
